openapi: 3.0.0
info:
  title: hola
  version: 1.0.0
paths:
  /upload:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                type:
                  type: string
                format:
                  type: binary
      responses:
        '200':
          description: Successful response
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  description:
                    type: File Uploaded successfully
        '402':
          description: Payment Required
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
